ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1 NOT NULL,
    ADD COLUMN IF NOT EXISTS date_of_joining DATE,
    ADD COLUMN IF NOT EXISTS created_by INTEGER NULL,
    ADD COLUMN IF NOT EXISTS last_modified_by INTEGER NULL;
