CREATE TABLE leave_policies (
    id SERIAL PRIMARY KEY,
    version integer DEFAULT 1 NOT NULL,
    leave_type_id BIGINT NOT NULL,
    leave_group_assign_id BIGINT NOT NULL,
    default_quota INTEGER,
    min_days INTEGER,
    max_days INTEGER,
    carry_forward_allowed BOOLEAN,
    carry_forward_cap INTEGER,
    encashable BOOLEAN,
    proof_required BOOLEAN,
    proof_threshold INTEGER,
    gender_restricted BOOLEAN,
    eligible_gender VARCHAR(10),
    tenure_required INTEGER,
    max_occurrences INTEGER,
    requires_approval BOOLEAN,
    expedited_approval BOOLEAN,
    linked_to_overtime BOOLEAN,
    created_by integer NULL,
    last_modified_by integer NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (leave_type_id) REFERENCES leave_types (id) ON DELETE CASCADE
);